// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA7xEpwW1VDUdm5FlEsvC7JONRJmKXPSk',
    appId: '1:666187227553:web:9e575dc6a6d3d649b7abe0',
    messagingSenderId: '666187227553',
    projectId: 'zappy-66d47',
    authDomain: 'zappy-66d47.firebaseapp.com',
    storageBucket: 'zappy-66d47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGP8V2y9iJdAHko38Vf3DaAnQEanYU-NE',
    appId: '1:666187227553:android:2c0a05d67fbb10e8b7abe0',
    messagingSenderId: '666187227553',
    projectId: 'zappy-66d47',
    storageBucket: 'zappy-66d47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq-11vv-S9nnE8L5_geL7oGBRX4H6qcbw',
    appId: '1:666187227553:ios:83bcca35326eeabbb7abe0',
    messagingSenderId: '666187227553',
    projectId: 'zappy-66d47',
    storageBucket: 'zappy-66d47.firebasestorage.app',
    iosBundleId: 'com.example.zappy',
  );
}
